[package]
name = "fhl"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "json2capn"
path = "src/json2capn.rs"

[dependencies]
capnp = "0.20.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
magnus = "0.7"
serde_magnus = "0.8.1"
